### ISSUE TITLE
segfaults in Docker

### ISSUE THREAD

**Issue by mikegleasonjr** [jdeng/goheif#1]
It is segfaulting in both alpine and stretch...

It is not segfaulting on my dev env on OSX. What's weird is that the segfaults happens when trying to write to jpeg the already decoded heic image.

To reproduce:

`Dockerfile`:

```
FROM golang:alpine3.8
RUN apk --no-cache add build-base git
RUN go get github.com/jdeng/goheif/...
WORKDIR /tmp
COPY test.heic .
CMD ["heic2jpg", "test.heic", "test.jpg"]
```

-or- 

```
FROM golang:stretch
RUN apt-get update && apt-get install -y build-essential git
RUN go get github.com/jdeng/goheif/...
WORKDIR /tmp
COPY test.heic .
CMD ["heic2jpg", "test.heic", "test.jpg"]
```

Then...

```
$ docker build -t test .
$ docker run -it --rm test
```

outputs:

```
2019/03/28 09:07:37 Warning: no EXIF from test.heic: heif: no EXIF found
unexpected fault address 0x7f6cc965b020
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f6cc965b020 pc=0x4d11dd]

goroutine 1 [running]:
runtime.throw(0x55d0a0, 0x5)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0000c12c8 sp=0xc0000c1298 pc=0x43bf62
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:397 +0x275 fp=0xc0000c1318 sp=0xc0000c12c8 pc=0x44eef5
image/jpeg.yCbCrToYCbCr(0xc0000a8100, 0x0, 0x0, 0xc0000c1418, 0xc0000c1918, 0xc0000c1518)
	/usr/local/go/src/image/jpeg/writer.go:461 +0x13d fp=0xc0000c1390 sp=0xc0000c1318 pc=0x4d11dd
image/jpeg.(*encoder).writeSOS(0xc0000b80c0, 0x576860, 0xc0000a8100)
	/usr/local/go/src/image/jpeg/writer.go:547 +0x398 fp=0xc0000c1d40 sp=0xc0000c1390 pc=0x4d1708
image/jpeg.Encode(0x576280, 0xc000091940, 0x576860, 0xc0000a8100, 0x0, 0x576280, 0xc000091940)
	/usr/local/go/src/image/jpeg/writer.go:634 +0x2b0 fp=0xc0000c1dc0 sp=0xc0000c1d40 pc=0x4d1c10
main.main()
	/go/src/github.com/jdeng/goheif/heic2jpg/main.go:92 +0x528 fp=0xc0000c1f98 sp=0xc0000c1dc0 pc=0x4d2be8
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc0000c1fe0 sp=0xc0000c1f98 pc=0x43d8d7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000c1fe8 sp=0xc0000c1fe0 pc=0x465bc1
```

The `heic` sample file is this one: http://jpgtoheif.com/camel.heic

**Comment by jdeng** [comment]
What is your OS environment? Can you try to uncomment a few lines in libde265/libde265.go like below? Not sure if it is related
```
                        ycc := &image.YCbCr{
-                               Y:  (*[1 << 30]byte)(unsafe.Pointer(y))[:int(height)*int(ystride)],
-                               Cb: (*[1 << 30]byte)(unsafe.Pointer(cb))[:int(cheight)*int(cstride)],
-                               Cr: (*[1 << 30]byte)(unsafe.Pointer(cr))[:int(cheight)*int(cstride)],
-                               //Y:              C.GoBytes(unsafe.Pointer(y), C.int(height*ystride)),
-                               //Cb:             C.GoBytes(unsafe.Pointer(cb), C.int(cheight*cstride)),
-                               //Cr:             C.GoBytes(unsafe.Pointer(cr), C.int(cheight*cstride)),
+                               //Y:  (*[1 << 30]byte)(unsafe.Pointer(y))[:int(height)*int(ystride)],
+                               //Cb: (*[1 << 30]byte)(unsafe.Pointer(cb))[:int(cheight)*int(cstride)],
+                               //Cr: (*[1 << 30]byte)(unsafe.Pointer(cr))[:int(cheight)*int(cstride)],
+                               Y:              C.GoBytes(unsafe.Pointer(y), C.int(height*ystride)),
+                               Cb:             C.GoBytes(unsafe.Pointer(cb), C.int(cheight*cstride)),
+                               Cr:             C.GoBytes(unsafe.Pointer(cr), C.int(cheight*cstride)),
                                YStride:        int(ystride),
                                CStride:        int(cstride),

```

**Comment by mikegleasonjr** [comment]
Yes it is not raising a segfault now like this:

```
ycc := &image.YCbCr{
    Y:  (*[1 << 30]byte)(unsafe.Pointer(y))[:int(height)*int(ystride)],
    Cb: (*[1 << 30]byte)(unsafe.Pointer(cb))[:int(cheight)*int(cstride)],
    Cr: (*[1 << 30]byte)(unsafe.Pointer(cr))[:int(cheight)*int(cstride)],
    //Y:              C.GoBytes(unsafe.Pointer(y), C.int(height*ystride)),
    //Cb:             C.GoBytes(unsafe.Pointer(cb), C.int(cheight*cstride)),
    //Cr:             C.GoBytes(unsafe.Pointer(cr), C.int(cheight*cstride)),
    YStride:        int(ystride),
    CStride:        int(cstride),
    SubsampleRatio: r,
    Rect:           image.Rectangle{Min: image.Point{0, 0}, Max: image.Point{int(width), int(height)}},
}
```

**Comment by mikegleasonjr** [comment]
@jdeng  I have a PR coming your way regarding image registration with `stdlib`, do you want me to integrate this change also in it?

**Comment by jdeng** [comment]
I would rather separate the changes and make this behavior optional as it is less memory efficient

**Comment by mikegleasonjr** [comment]
Ok will create 2 PRs and feature flag.

How would you call that switching behavior?
